name = "perturbing/sudoku-bounty"
version = "0.0.0"
compiler = "v1.1.19"
plutus = "v3"
license = "Apache-2.0"
description = "Zero-knowledge Sudoku challenge-and-solve on Cardano"

[repository]
user = "perturbing"
project = "sudoku-bounty"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.0.0"
source = "github"
