name = "perturbing/aiken-plonk"
version = "0.0.0"
compiler = "v1.1.19"
plutus = "v3"
license = "Apache-2.0"
description = "An Aiken PLONK verifier using Circom and SnarkJS"

[repository]
user = "perturbing"
project = "aiken-plonk"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.0.0"
source = "github"
