// On-chain interaction for sudoku challenges using Lucid Evolution + Blockfrost.
// Requires Vite (or another bundler) to resolve the @lucid-evolution WASM dependency.

// Lucid is loaded lazily via dynamic import so Rollup places it in a separate
// chunk. That chunk has TLA for CML/UPLC WASM init, and the browser resolves
// it fully before this code runs — avoiding "Class extends value undefined".
import { blake2b } from '@noble/hashes/blake2b';

let _lucid = null;
async function getLucid() {
  if (!_lucid) {
    const m = await import('@lucid-evolution/lucid');
    _lucid = {
      ...m,
      ChallengeDatumSchema: m.Data.Object({
        board_id:      m.Data.Integer(),
        board_encoded: m.Data.Bytes(),
        publisher_pkh: m.Data.Bytes(),
      }),
    };
  }
  return _lucid;
}

// ---------------------------------------------------------------------------
// Script constants  (generated by: aiken blueprint apply -v plonk_challenge.spend)
// ---------------------------------------------------------------------------

export const SCRIPT_HASH    = 'e148dfba00dba24086d33451fd56fcf4db777c47472d27a9ec9cc81c';
export const SCRIPT_ADDRESS = 'addr1w8s53ha6qrd6ysyx6v69rl2kln6dkamugarj6fafajwvs8qjv06u4';
const SCRIPT_CBOR ='590f0d0101003229800aba2aba1aba0aab9faab9eaab9dab9a9bc248816093e02b6052719f607dacd3a088274f65596bd0d09920b61ab5da61bbdc7f5049334cf11213945d57e5ac7d055d042b7e024aa2b2f08f0a91260805272dc51051c6e47ad4fa403b02b4510b647ae3d1770bac0326a805bbefd48056c8c121bdb8009bbb48813097f1d3a73197d7942695638c4fa9ac0fc3688c4f9774b905a14e3a3f171bac586c55e83ff97a1aeffb3af00adb22c6bb0048888888896600264653001300a300b0019b874800a60140049112cc004c008c024dd5001c4cc88ca60026020003301030110039808001a444b30013014004899198009bac3014006225980080144c966002600260266ea801e26464646464646464646464646464653001375a604c00330270019bae302600f9bae302600e9bae302600d9bae302600c9bae302600b9bae302600a9bae30260099bae30260089bae30260079bad30260069bad30260059bad30260049bad30260039bad30260024888888888888888966002606e01f1330233758606c01e44b30010028992cc004c08cc0d4dd5000c4c96600266e1d2004303637546002606e6ea8c0e8c0ecc0dcdd5181d181b9baa0028acc004c090c0d8dd5014c4c9660026466446600400400244b30010018a508acc004cdc79bae303e0010038a51899801001181f800a07240f06eb0c0f0c0f4c0f4c0f4c0f4c0f4c0f4c0f4c0f4c0e4dd50181bae30023038375400314a31325980099b87375a60780026eb4c0f0c0e4dd50014660024466e18cdc1001000a4105010101c1fffffffff7bfcbff7f0349f79d550177d1091161cf330753bf9d534d3bdb7c1d2232330010010032259800800c52f5c113303f375060066eb4c100004cc008008c10400503e48cdc319bca4a20029041404040707ffffffffdeff2ffdfc0d27de755405df442445873ccc1d4efe754d34ef6df0748ca6002003002a441004004444b30010028800c66002007304100299b8a001375c6080004801903e488cdc319b810020014820a02020383ffffffffef7f97fefe0693ef3aaa02efa21222c39e660ea77f3aa69a77b6f83a444653001001802400d0011112cc00400a297ae08acc004006297ae08998209ba833004375a60840046eb4c108006600200730430029821800a00641008202466e18cdc0a4105010101c1fffffffff7bfcbff7f0349f79d550177d1091161cf330753bf9d534d3bdb7c1c0029041404040707ffffffffdeff2ffdfc0d27de755405df442445873ccc1d4efe754d34ef6df07488cdc319b800020014820a02020383ffffffffef7f97fefe0693ef3aaa02efa21222c39e660ea77f3aa69a77b6f83a4466ed8008ddb800cc0e4dd501fcc0e4dd5181e181e8172444444444453001225980099b88001480022900044ca6002003003801200222259800981b000c400a33001003998080010014cdc0000a40028019047208898240014c1200066eb8c11c006660140184600c66e180052082808080e0fffffffffbdfe5ffbf81a4fbceaa80bbe88488b0e79983a9dfcea9a69dedbe0e99b86375a608e0049041404040707ffffffffdeff2ffdfc0d27de755405df442445873ccc1d4efe754d34ef6df072444444664466446645300130540029bae3053002982a000cdd71829800a4445300130580049bae3057004982c0014dd7182b801244453001305c0049bae305b004982e0014dd7182d80124445300130600049bae305f00498300014dd7182f80124445300130640049bae306300498320014dd718318014ddd800a44445300130690059bae30680059834801cdd69834001cddd8014c0a8de419b8a006002488888a600260de00d375c60dc00d306f0049bad306e00499b860034820a02020383ffffffffef7f97fefe0693ef3aaa02efa21222c39e660ea77f3aa69a77b6f839222229800983a002cdd71839802cc1d000e6eb4c1cc00e66e180092082808080e0fffffffffbdfe5ffbf81a4fbceaa80bbe88488b0e79983a9dfcea9a69dedbe0e9bae307302a9bae30730254888888a60026eb0c1e8c1ec01e60f600b375a60f400b3370c0089041404040707ffffffffdeff2ffdfc0d27de755405df442445873ccc1d4efe754d34ef6df074c0f0de4181d9983c9ba9026330793752044660f26ea4078cc1e4dd480d1983c9ba9016330793752022660f26ea402ccc1e4dd48031983c9ba9329800800c1029101004004444b30010028800c66002007307e00299b8a0019800a51a4081375a60fa004bc9200641ec660f26ea40c0cc1e4dd48011983c9ba90014bd7024444530013080010049bad307f00499b860034820a02020383ffffffffef7f97fefe0693ef3aaa02efa21222c39e660ea77f3aa69a77b6f83a60826f226002946902040057929bae307f02f48888a60026eb4c2100401666e180112082808080e0fffffffffbdfe5ffbf81a4fbceaa80bbe88488b0e79983a9dfcea9a69dedbe0e998239bac30840130850100523370c0029041404040707ffffffffdeff2ffdfc0d27de755405df442445873ccc1d4efe754d34ef6df074c118de4182299841809ba99800a51a40810065e48cc20c04dd4cc00528d20408012f2466106026ea40052f5c133041012002998208068014cc10401c00a6609000c006911111114c004cdc300424105010101c1fffffffff7bfcbff7f0349f79d550177d1091161cf330753bf9d534d3bdb7c1d304e3790609a66116026ea66002946902040157923308b01375206c66116026ea40c8cc22c04dd481725eb82660a000a00b3305000e0074888a600260a46f20c144cc23c04dd4cc00528d2040801af246611e026ea66002946902040957923308f01375330014a34810203ebc919847809ba99800a51a408101a5e48cc23c04dd4cc00528d204080a2f246611e026ea66002946902040417923308f01375330014a348102018bc925eb82660920066eb4c24004122660a80120093305401200348888c8c8c96600266f18cde219bb6030337700540566f08dd7184b8081219bc4330533376c66ed8cddc00501819bb83305b3305b02a00a3370c6eb4c25c04c260040752082808080e0fffffffffbdfe5ffbf81a4fbceaa80bbe88488b0e79983a9dfcea9a69dedbe0e02b3376c660a6660a666ed8cddb19bb63376c66ed8cddc1982d8128101bbb0433377004a6eec0fccddc0101bbb03b337700346eec0dcddd81999bb833054330543305b3305b3305b3305400f0043305400e3305b0043370c6eb4c25c041292082808080e0fffffffffbdfe5ffbf81a4fbceaa80bbe88488b0e79983a9dfcea9a69dedbe0e3305400d3305b0043370c6eb4c25c041212082808080e0fffffffffbdfe5ffbf81a4fbceaa80bbe88488b0e79983a9dfcea9a69dedbe0e0103305b00100902a377602866ee0cc16ccc16ccc16ccc15003c030cc150038020014064ddd81199bb80033376c66ed8ddd82099bb8006377607a66ee0cc1400192002377607266ee001ccddb1bbb04d3377000e66ed8ddd80f99bb80073376c6eec078cddc00399bb6377605c66ee001cddd81419bb8330543305430553305733057330543305b375a612e02098002653001001cc004c2640413661320200705c415d3370c900024105010101c1fffffffff7bfcbff7f0349f79d550177d1091161cf330753bf9d534d3bdb7c1c80088896600200510018cc00400e61360200533057001375a6134020048019098011982d8008049982d9982d9982d8029982a0078061982a0070040069982d8039982a0129982d8039982a0101982d8039982a00d1982d8039982a00b1982d8038091982d8150058480084880c4c8cc004004ca60020030139982e00f919b860014820a02020383ffffffffef7f97fefe0693ef3aaa02efa21222c39e660ea77f3aa69a77b6f8390011112cc00400a297ae08acc004006297ae089984d00cc004c24004cc17ccc17cdd6984d808010279982d8071bad309b01001a60103d87a8000a60103d87980004258053001003984e008014c2700400500321320242640444b30010018a518acc004c23804c25404dd5184c80800c4cc008008c26804006294109401212e028a504248046eb4c25804006600203700f911982d9982d99b860024820a02020383ffffffffef7f97fefe0693ef3aaa02efa21222c39e660ea77f3aa69a77b6f83800c0050541982a001a40040003052002305200130500023050001304e005304e004229410371bac303b02d40d86074606e6ea80a629450354528a06a2303a303b303b0018b2068323300100137586072606c6ea80b4896600200314c0103d87a80008992cc004cdd7981d981c1baa001029899ba548000cc0e80052f5c1133003003303c00240d8607400281c2264600460740066eb4c0e00090364590340c098004c094004c090004c08c004c088004c084004c080004c07c004c078004c074004c070004c06c004c068004c064004c050dd5003c590121b8748002264600460300066eb4c058009014111919800800801911980180098010014590110c040004c028dd50019bac300d0048b2010180500098029baa00a8a4d13656400c4c01ffd8798e1a000200001102035830b7bd9315060282b392aacb5f2b91d182c1488b417e088e0b48b9fa8817318212f57d9ef7e32bbe18a0ec2d8c6689e6185830a89c1c7c35fa5ed3107fcd5a6f965ffc6339e5b21fd5f8a84e9f04331ff5371f0316ed2079b3ee93880fc41f1a963f9d5830af7c07882afd0d46027217e927fa8d4bed62cd109341d7c62e01e9be22a067be11abfaa3fd0da26a051739c8b1e30d595830b904657a22b7ec368b3691b54d0f0d4ba500d065dde5f90dbec2080acfdef9d70a9bc987b1689d2f8c129f6034b0cf1b583087c904599b7069698cc80c0788757e4170e78b4336f739b98293d8be1fadd5acb37f954df183070b1fe7ff2342ee7bd9df5830933aa7d3a3385ff1a24dd1949b0f5014798c7c2ef0746fe5b75ff118d4d76ac68d0e6117ee6973ed122bf261eaca67d05830b8271b309753a8c3f05f16e90bf92615dd1f6bc6765d6694fb0313c972fc672301288f9d542ccee565c1f0c474fe30e65830b76717e56ba9c5950314d4c2d420e698aa00545ea231d877020387524f0cdfd733274c4bbd212a6d896c9e174fc5e5ab5f584091b4cc8115f207af30054aed5d4c7699a8b7c05f03f5defff83941caa7d6c05b11cd620c3b92a39ad350c1b7ac4c3d38059a6c034af845fb86c02fc1bb0d3e3958200e405751e280c30fa9a4fc6876ade90128e0f62fc26ad28f771e18e2147a287ed0ff8201c2582005deb333f8727901ebe905bd4fb9ac5c77d85a937ff858ec10251f7d8831e03e0001';

const NETWORK = 'Mainnet';
const BLOCKFROST_URL = 'https://cardano-mainnet.blockfrost.io/api/v0';


// ---------------------------------------------------------------------------
// BLS12-381 constants (for challenge / Lagrange computation)
// ---------------------------------------------------------------------------

const Fp = 4002409555221667393417789825735904156556882819939007885332058136124031650490837864442687629129015664037894272559787n;
const Fr = 52435875175126190479447740508185965837690552500527637822603658699938581184513n;

// ---------------------------------------------------------------------------
// G1 compression (ZCash / BLST serialisation)
// ---------------------------------------------------------------------------

function compressG1(x_str, y_str) {
  const x = BigInt(x_str), y = BigInt(y_str);
  let val = x | (1n << 383n);
  if (y * 2n > Fp) val |= (1n << 381n);
  return hexToBytes(val.toString(16).padStart(96, '0'));
}

function hexToBytes(hex) {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < hex.length; i += 2) out[i >> 1] = parseInt(hex.slice(i, i + 2), 16);
  return out;
}

function bytesConcat(...arrays) {
  const total = arrays.reduce((s, a) => s + a.length, 0);
  const out = new Uint8Array(total);
  let off = 0;
  for (const a of arrays) { out.set(a, off); off += a.length; }
  return out;
}

function bigintToBeBytes(n) {
  const hex = n.toString(16);
  return hexToBytes(hex.length % 2 ? '0' + hex : hex);
}

function intToBE32(n) {
  return hexToBytes(n.toString(16).padStart(64, '0'));
}

function bytesToBigInt(buf) {
  let n = 0n;
  for (const b of buf) n = (n << 8n) | BigInt(b);
  return n;
}

function modFr(n) { return ((n % Fr) + Fr) % Fr; }

function modPow(base, exp, mod) {
  let result = 1n; base = base % mod;
  while (exp > 0n) {
    if (exp % 2n === 1n) result = result * base % mod;
    exp >>= 1n; base = base * base % mod;
  }
  return result;
}

function modInverse(a, m) { return modPow(((a % m) + m) % m, m - 2n, m); }

function blake2b224(buf) {
  return blake2b(buf, { dkLen: 28 });
}

// ---------------------------------------------------------------------------
// Fiat-Shamir challenges (must match on-chain verifier exactly)
// ---------------------------------------------------------------------------

function computeZeta(pre, proof_c, pubInputs) {
  const pubBytes = bytesConcat(...pubInputs.map(intToBE32));
  const betaInput = bytesConcat(
    pre.q_m, pre.q_l, pre.q_r, pre.q_o, pre.q_c,
    pre.s_sig1, pre.s_sig2, pre.s_sig3,
    pubBytes,
    proof_c.commitment_a, proof_c.commitment_b, proof_c.commitment_c,
  );
  const beta  = bytesToBigInt(blake2b224(betaInput)) % Fr;
  const gamma = bytesToBigInt(blake2b224(intToBE32(beta))) % Fr;
  const alpha = bytesToBigInt(blake2b224(bytesConcat(intToBE32(beta), intToBE32(gamma), proof_c.commitment_z))) % Fr;
  const zeta  = bytesToBigInt(blake2b224(bytesConcat(intToBE32(alpha), proof_c.t_low, proof_c.t_mid, proof_c.t_high))) % Fr;
  return zeta;
}

function computeLagrangeInverses(n_val, zeta, gens) {
  return gens.map(gen_i => modInverse(modFr(BigInt(n_val) * modFr(zeta - gen_i)), Fr));
}

// ---------------------------------------------------------------------------
// Minimal CBOR encoder for Plutus Data
// ---------------------------------------------------------------------------

function cborBytesHeader(len) {
  const n = BigInt(len);
  if (n < 24n) return new Uint8Array([0x40 | len]);
  if (n < 0x100n) return new Uint8Array([0x58, len]);
  return new Uint8Array([0x59, len >> 8, len & 0xff]);
}

function cborBytes(buf) { return bytesConcat(cborBytesHeader(buf.length), buf); }

function cborUInt(n) {
  if (n < 24n) return new Uint8Array([Number(n)]);
  if (n < 0x100n) return new Uint8Array([0x18, Number(n)]);
  if (n < 0x10000n) return new Uint8Array([0x19, Number(n >> 8n), Number(n & 0xffn)]);
  if (n < 0x100000000n) return new Uint8Array([0x1a, Number(n>>24n), Number((n>>16n)&0xffn), Number((n>>8n)&0xffn), Number(n&0xffn)]);
  if (n < 0x10000000000000000n) {
    const b = new Uint8Array(9); b[0] = 0x1b;
    const hi = Number(n >> 32n), lo = Number(n & 0xffffffffn);
    b[1]=(hi>>24)&0xff; b[2]=(hi>>16)&0xff; b[3]=(hi>>8)&0xff; b[4]=hi&0xff;
    b[5]=(lo>>24)&0xff; b[6]=(lo>>16)&0xff; b[7]=(lo>>8)&0xff; b[8]=lo&0xff;
    return b;
  }
  const valueBytes = bigintToBeBytes(n);
  return bytesConcat(new Uint8Array([0xc2]), cborBytesHeader(valueBytes.length), valueBytes);
}

function cborInt(n) {
  if (n >= 0n) return cborUInt(n);
  const m = -(n + 1n);
  if (m < 0x10000000000000000n) {
    const enc = cborUInt(m).slice(); enc[0] |= 0x20; return enc;
  }
  const valueBytes = bigintToBeBytes(m);
  return bytesConcat(new Uint8Array([0xc3]), cborBytesHeader(valueBytes.length), valueBytes);
}

function cborArray(items) {
  const n = items.length;
  let header;
  if (n < 24) header = new Uint8Array([0x80 | n]);
  else if (n < 256) header = new Uint8Array([0x98, n]);
  else header = new Uint8Array([0x99, n >> 8, n & 0xff]);
  return bytesConcat(header, ...items);
}

function cborConstr0(fields) {
  return bytesConcat(new Uint8Array([0xd8, 0x79]), cborArray(fields));
}

// ---------------------------------------------------------------------------
// Proof encoding (matches Aiken Proof type field order)
// ---------------------------------------------------------------------------

function encodeProof(p) {
  return cborConstr0([
    cborBytes(p.commitment_a),
    cborBytes(p.commitment_b),
    cborBytes(p.commitment_c),
    cborBytes(p.commitment_z),
    cborBytes(p.t_low),
    cborBytes(p.t_mid),
    cborBytes(p.t_high),
    cborBytes(p.w_omega),
    cborBytes(p.w_omega_zeta),
    cborInt(p.a_eval),
    cborInt(p.b_eval),
    cborInt(p.c_eval),
    cborInt(p.s_sig1_eval),
    cborInt(p.s_sig2_eval),
    cborInt(p.z_omega_eval),
    cborArray(p.lagrange_inverses.map(li => cborInt(li))),
  ]);
}

function encodeRedeemer(pubInputs, proof) {
  return cborArray([
    cborArray(pubInputs.map(x => cborInt(x))),
    encodeProof(proof),
  ]);
}

// ---------------------------------------------------------------------------
// Board encoding / decoding (matches boardId.js encodeBoard)
// ---------------------------------------------------------------------------

export function encodeBoard(board) {
  const bytes = new Uint8Array(41);
  bytes[0] = board[0][0];
  for (let k = 1; k <= 40; k++) {
    const cell1 = board[Math.floor((2 * k - 1) / 9)][(2 * k - 1) % 9];
    const cell2 = board[Math.floor((2 * k) / 9)][(2 * k) % 9];
    bytes[k] = (cell1 << 4) | cell2;
  }
  return bytes;
}

export function decodeBoard(bytes) {
  const board = Array.from({ length: 9 }, () => new Array(9).fill(0));
  board[0][0] = bytes[0] & 0x0f;
  for (let k = 1; k <= 40; k++) {
    const cell1 = (bytes[k] >> 4) & 0x0f;
    const cell2 = bytes[k] & 0x0f;
    board[Math.floor((2 * k - 1) / 9)][(2 * k - 1) % 9] = cell1;
    board[Math.floor((2 * k) / 9)][(2 * k) % 9] = cell2;
  }
  return board;
}

// ---------------------------------------------------------------------------
// Lucid helpers
// ---------------------------------------------------------------------------

async function makeLucid(blockfrostKey) {
  const { Lucid, Blockfrost } = await getLucid();
  return Lucid(new Blockfrost(BLOCKFROST_URL, blockfrostKey), NETWORK);
}

async function connectEternl(lucid) {
  if (!window.cardano?.eternl) throw new Error('Eternl wallet not found. Please install the Eternl extension.');
  const api = await window.cardano.eternl.enable();
  lucid.selectWallet.fromAPI(api);
  return lucid;
}

// ---------------------------------------------------------------------------
// Deploy challenge
// ---------------------------------------------------------------------------

export async function deployChallenge(blockfrostKey, board, boardId, lovelace) {
  const { Data, toHex, getAddressDetails, ChallengeDatumSchema } = await getLucid();
  const lucid = await connectEternl(await makeLucid(blockfrostKey));

  const walletAddress = await lucid.wallet().address();
  const { paymentCredential } = getAddressDetails(walletAddress);
  if (!paymentCredential) throw new Error('Could not read payment credential from wallet address.');
  const publisherPkh = paymentCredential.hash;

  const boardEncoded = encodeBoard(board);
  const datum = Data.to(
    {
      board_id:      BigInt(boardId),
      board_encoded: toHex(boardEncoded),
      publisher_pkh: publisherPkh,
    },
    ChallengeDatumSchema,
  );

  const tx = await lucid.newTx()
    .pay.ToAddressWithData(
      SCRIPT_ADDRESS,
      { kind: 'inline', value: datum },
      { lovelace: BigInt(lovelace) },
    )
    .complete();

  const signed = await tx.sign.withWallet().complete();
  return signed.submit();
}

// ---------------------------------------------------------------------------
// Fetch challenges (Blockfrost UTxO query)
// ---------------------------------------------------------------------------

export async function fetchChallenges(blockfrostKey) {
  const { Data, fromHex, ChallengeDatumSchema } = await getLucid();
  const resp = await fetch(
    `${BLOCKFROST_URL}/addresses/${SCRIPT_ADDRESS}/utxos`,
    { headers: { project_id: blockfrostKey } },
  );
  if (resp.status === 404) return [];
  if (!resp.ok) throw new Error(`Blockfrost error: ${resp.status} ${resp.statusText}`);
  const utxos = await resp.json();

  const challenges = [];
  for (const utxo of utxos) {
    if (!utxo.inline_datum) continue;
    try {
      const decoded = Data.from(utxo.inline_datum, ChallengeDatumSchema);
      const boardEncoded = fromHex(decoded.board_encoded);
      challenges.push({
        txHash:       utxo.tx_hash,
        outputIndex:  utxo.output_index,
        boardId:      decoded.board_id.toString(),
        boardEncoded,
        board:        decodeBoard(boardEncoded),
        publisherPkh: decoded.publisher_pkh,
        lovelace:     BigInt(utxo.amount.find(a => a.unit === 'lovelace').quantity),
      });
    } catch (_) {
      // Not a valid ChallengeDatum — skip
    }
  }
  return challenges;
}

// ---------------------------------------------------------------------------
// Claim challenge (spend UTxO with PLONK proof)
// ---------------------------------------------------------------------------

let _vkCache = null;
async function loadVK() {
  if (!_vkCache) {
    const r = await fetch(import.meta.env.BASE_URL + 'verification_key.json');
    if (!r.ok) throw new Error('Could not load verification_key.json');
    _vkCache = await r.json();
  }
  return _vkCache;
}

function buildProofCompressed(proofJson, vkJson, pubInputs) {
  function generatorPowers(omega_str, nPublic) {
    const omega = BigInt(omega_str);
    const powers = []; let cur = 1n;
    for (let i = 0; i <= nPublic; i++) { powers.push(modFr(cur)); cur = modFr(cur * omega); }
    return powers;
  }

  const n_val = Math.pow(2, vkJson.power);
  const gens  = generatorPowers(vkJson.w, vkJson.nPublic);

  const pre = {
    q_m:    compressG1(vkJson.Qm[0], vkJson.Qm[1]),
    q_l:    compressG1(vkJson.Ql[0], vkJson.Ql[1]),
    q_r:    compressG1(vkJson.Qr[0], vkJson.Qr[1]),
    q_o:    compressG1(vkJson.Qo[0], vkJson.Qo[1]),
    q_c:    compressG1(vkJson.Qc[0], vkJson.Qc[1]),
    s_sig1: compressG1(vkJson.S1[0], vkJson.S1[1]),
    s_sig2: compressG1(vkJson.S2[0], vkJson.S2[1]),
    s_sig3: compressG1(vkJson.S3[0], vkJson.S3[1]),
  };

  const proof_c = {
    commitment_a:   compressG1(proofJson.A[0],   proofJson.A[1]),
    commitment_b:   compressG1(proofJson.B[0],   proofJson.B[1]),
    commitment_c:   compressG1(proofJson.C[0],   proofJson.C[1]),
    commitment_z:   compressG1(proofJson.Z[0],   proofJson.Z[1]),
    t_low:          compressG1(proofJson.T1[0],  proofJson.T1[1]),
    t_mid:          compressG1(proofJson.T2[0],  proofJson.T2[1]),
    t_high:         compressG1(proofJson.T3[0],  proofJson.T3[1]),
    w_omega:        compressG1(proofJson.Wxi[0], proofJson.Wxi[1]),
    w_omega_zeta:   compressG1(proofJson.Wxiw[0],proofJson.Wxiw[1]),
    a_eval:         BigInt(proofJson.eval_a),
    b_eval:         BigInt(proofJson.eval_b),
    c_eval:         BigInt(proofJson.eval_c),
    s_sig1_eval:    BigInt(proofJson.eval_s1),
    s_sig2_eval:    BigInt(proofJson.eval_s2),
    z_omega_eval:   BigInt(proofJson.eval_zw),
  };

  const zeta = computeZeta(pre, proof_c, pubInputs);
  proof_c.lagrange_inverses = computeLagrangeInverses(n_val, zeta, gens);
  return proof_c;
}

// ---------------------------------------------------------------------------
// Retract challenge (publisher reclaims their UTxO)
// ---------------------------------------------------------------------------

export async function retractChallenge(blockfrostKey, challenge) {
  const { toHex, getAddressDetails } = await getLucid();
  const lucid = await connectEternl(await makeLucid(blockfrostKey));

  const walletAddress = await lucid.wallet().address();
  const { paymentCredential } = getAddressDetails(walletAddress);
  if (!paymentCredential) throw new Error('Could not read payment credential from wallet.');
  if (paymentCredential.hash !== challenge.publisherPkh)
    throw new Error('Connected wallet is not the publisher of this challenge.');

  // The validator returns True on the signed_by_publisher path before using the
  // redeemer, but Aiken deserialises it at entry, so we must pass a structurally
  // valid (List<Int>, Proof) even though every field is a dummy zero value.
  const zero48 = new Uint8Array(48);
  const dummyProof = {
    commitment_a: zero48, commitment_b: zero48, commitment_c: zero48,
    commitment_z: zero48, t_low: zero48, t_mid: zero48, t_high: zero48,
    w_omega: zero48, w_omega_zeta: zero48,
    a_eval: 0n, b_eval: 0n, c_eval: 0n,
    s_sig1_eval: 0n, s_sig2_eval: 0n, z_omega_eval: 0n,
    lagrange_inverses: [],
  };
  const redeemerHex = toHex(encodeRedeemer([], dummyProof));

  const script = { type: 'PlutusV3', script: SCRIPT_CBOR };
  const utxos = await lucid.utxosByOutRef([{ txHash: challenge.txHash, outputIndex: challenge.outputIndex }]);
  if (!utxos.length) throw new Error('UTxO not found (already spent?)');

  const tx = await lucid.newTx()
    .collectFrom(utxos, redeemerHex)
    .attach.SpendingValidator(script)
    .addSigner(walletAddress)
    .complete({ localUPLCEval: false });

  const signed = await tx.sign.withWallet().complete();
  return signed.submit();
}

// ---------------------------------------------------------------------------
// Claim challenge (spend UTxO with PLONK proof)
// ---------------------------------------------------------------------------

export async function claimChallenge(blockfrostKey, challenge, proofJson) {
  const { toHex } = await getLucid();
  const lucid = await connectEternl(await makeLucid(blockfrostKey));

  const vkJson = await loadVK();
  const pubInputs = [BigInt(challenge.boardId)];
  const proof_c = buildProofCompressed(proofJson, vkJson, pubInputs);
  const redeemerBytes = encodeRedeemer(pubInputs, proof_c);
  const redeemerHex = toHex(redeemerBytes);

  const script = { type: 'PlutusV3', script: SCRIPT_CBOR };

  const utxos = await lucid.utxosByOutRef([{
    txHash: challenge.txHash,
    outputIndex: challenge.outputIndex,
  }]);
  if (!utxos.length) throw new Error('UTxO not found (already spent?)');

  const tx = await lucid.newTx()
    .collectFrom(utxos, redeemerHex)
    .attach.SpendingValidator(script)
    .complete({ localUPLCEval: false });

  const signed = await tx.sign.withWallet().complete();
  return signed.submit();
}
